import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Columns from "@/components/Columns.jsx";
import Video from "@/components/Video.jsx";
import Header from "@/components/Header.jsx";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hilltop Manor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Video />
      <div
        name="header-container-full-width"
        style={{
          display: "flex",
          margin: "0 auto",
          flex: 1,
          position: "fixed",
          alignItems: "center",
          backgroundColor: "white",
          width: "100vw",
          height: "9.5vh",
        }}
      ></div>
      <div
        name="main-container"
        style={{
          display: "flex",
          position: "relative",
          marginTop: ".50rem",
          margin: "0 auto",
          // justifyContent: "center",
          flexWrap: "wrap",
          flex: 1,
          width: "66vw",
          minHeight: "100vh",
          backgroundColor: "translucent",
        }}
      >
        {/* <Columns /> */}
        <div
          name="header-container-placeholder-in-main"
          style={{
            display: "flex",
            margin: "0 auto",
            flex: 1,
            alignItems: "center",
            backgroundColor: "translucent",
            width: "100vw",
            height: "9.5vh",
          }}
        ></div>

        <Header />
        <div
          name="video-place-holder"
          style={{
            width: "99.1vw",
            height: "90vh",
            display: "flex",
            backgroundColor: "translucent",
          }}
        ></div>
        {/* <Video /> */}
        <div
          name="Welcome-card-container"
          style={{
            display: "flex",
            justifyContent: "center",
            marginTop: "5vw",
          }}
        >
          <div
            name="Welcome-card-left-text"
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
              width: "21vw",
              height: "60vh",
              backgroundColor: "translucent",
              padding: "2rem", // Add padding to all sides
              boxSizing: "border-box", // Include padding in the total width and height
              color: "#48021e",
              fontSize: "2rem",
              textAlign: "center",
              fontFamily: "EB Garamond, sans-serif",
              fontWeight: "400",
              letterSpacing: "0.2rem",
              backgroundColor: "rgb(234, 234, 234)",
            }}
          >
            <p style={{ marginBottom: "0.5rem" }}>WELCOME TO THE MANOR</p>
            <div
              style={{
                display: "flex",
                fontSize: "1.1rem",
                flexDirection: "column",
                justifyContent: "center",
                textAlign: "center",
                fontFamily: "EB Garamond, sans-serif",
                letterSpacing: "0.05rem",
                fontWeight: "400",
              }}
            >
              <p>
                Multi-Award-Winning Five Star Historic Country House & Estate.
                Crammed full of historical charm, sprinkled in literary mystique
                and bursting with 'la dolce vita' - The first Georgian built
                Italian style villa in North Wales.
              </p>
            </div>
          </div>
          <div
            name="Welcome-card-right-image"
            style={{
              display: "flex",
              justifyContent: "center",
              width: "45vw",
              height: "60vh",
              backgroundColor: "translucent",
              cursor: "pointer",
            }}
          >
            <img
              src="images/plasoutside.jpg"
              style={{
                width: "100%",
                height: "100%",
                objectFit: "cover",
              }}
            ></img>
          </div>
        </div>
        <div
          name="card-div-2-3"
          style={{
            display: "flex",
            justifyContent: "space-between",
            backgroundColor: "translucent",
            width: "66vw",
            height: "50vh",
            marginTop: "3vw",
          }}
        >
          <div
            name="card-container2"
            style={{
              display: "flex",
              justifyContent: "center",
            }}
          >
            <div
              name="card-left-text"
              style={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                width: "15.8vw",
                height: "50vh",
                backgroundColor: "translucent",
                color: "#48021e",
                backgroundColor: "translucent",
                borderTop: "1px solid #EAEAEA",
                borderBottom: "1px solid #EAEAEA",
                borderLeft: "1px solid #EAEAEA",
                padding: "2rem", // Add padding to all sides
                boxSizing: "border-box", // Include padding in the total width and height
                fontSize: "2rem",
                textAlign: "center",
                fontFamily: "EB Garamond, sans-serif",
                fontWeight: "400",
                letterSpacing: "0.2rem",
              }}
            >
              <p style={{ marginBottom: "0.5rem" }}>DINING OPTIONS</p>
              <div
                style={{
                  display: "flex",
                  fontSize: "1.1rem",
                  flexDirection: "column",
                  justifyContent: "center",
                  textAlign: "center",
                  fontFamily: "EB Garamond, sans-serif",
                  letterSpacing: "0.05rem",
                  fontWeight: "400",
                }}
              >
                <p>
                  Mesmerizing breakfast views and an award winning local
                  restaurant.
                </p>
              </div>
            </div>
            <div
              name="card-right-image"
              style={{
                display: "flex",
                justifyContent: "center",
                width: "15.8vw",
                height: "50vh",
                backgroundColor: "translucent",
                cursor: "pointer",
              }}
            >
              <img
                src="images/plasdiningoptions.jpg"
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                }}
              ></img>
            </div>
          </div>
          <div
            name="card-container3"
            style={{
              display: "flex",
              justifyContent: "space-between",
              backgroundColor: "translucent",
            }}
          >
            <div
              name="card-left-text"
              style={{
                display: "flex",
                flexDirection: "column",
                justifyContent: "center",
                alignItems: "center",
                width: "15.8vw",
                height: "50vh",
                backgroundColor: "translucent",
                color: "#48021e",
                backgroundColor: "translucent",
                borderTop: "1px solid #EAEAEA",
                borderBottom: "1px solid #EAEAEA",
                borderLeft: "1px solid #EAEAEA",
                padding: "2rem", // Add padding to all sides
                boxSizing: "border-box", // Include padding in the total width and height
                fontSize: "2rem",
                textAlign: "center",
                fontFamily: "EB Garamond, sans-serif",
                fontWeight: "400",
                letterSpacing: "0.2rem",
              }}
            >
              <p style={{ marginBottom: "0.5rem" }}>SIGHTS & ATTRACTIONS</p>
              <div
                style={{
                  display: "flex",
                  fontSize: "1.1rem",
                  flexDirection: "column",
                  justifyContent: "center",
                  textAlign: "center",
                  fontFamily: "EB Garamond, sans-serif",
                  letterSpacing: "0.05rem",
                  fontWeight: "400",
                }}
              >
                <p>
                  Ideally placed for all the attractions that North Wales has to
                  offer.
                </p>
              </div>
            </div>
            <div
              name="card-right-image"
              style={{
                display: "flex",
                justifyContent: "center",
                width: "15.8vw",
                height: "50vh",
                backgroundColor: "translucent",
                cursor: "pointer",
              }}
            >
              <img
                src="images/plasattractions.jpg"
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                }}
              ></img>
            </div>
          </div>
        </div>
        <div
          name="card-container4"
          style={{
            display: "flex",
            justifyContent: "center",
            marginTop: "6vh",
          }}
        >
          <div
            name="card-left-image"
            style={{
              display: "flex",
              justifyContent: "center",
              width: "45vw",
              height: "60vh",
              backgroundColor: "translucent",
              cursor: "pointer",
            }}
          >
            <img
              src="images/plashistory.jpg"
              style={{
                width: "100%",
                height: "100%",
                objectFit: "cover",
              }}
            ></img>
          </div>
          <div
            name="card-right-text"
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignItems: "center",
              width: "21vw",
              height: "60vh",
              backgroundColor: "translucent",
              padding: "2rem", // Add padding to all sides
              boxSizing: "border-box", // Include padding in the total width and height
              color: "#48021e",
              fontSize: "2rem",
              textAlign: "center",
              fontFamily: "EB Garamond, sans-serif",
              fontWeight: "400",
              letterSpacing: "0.2rem",
              backgroundColor: "rgb(234, 234, 234)",
            }}
          >
            <p style={{ marginBottom: "0.5rem" }}>
              THE HISTORY BEHIND HILLTOP MANOR
            </p>
            <div
              style={{
                display: "flex",
                fontSize: "1.1rem",
                flexDirection: "column",
                justifyContent: "center",
                textAlign: "center",
                fontFamily: "EB Garamond, sans-serif",
                letterSpacing: "0.05rem",
                fontWeight: "400",
              }}
            >
              <p>
                Built in the early 1800s, Hilltop Manor has a deep historical
                connection to North Wales. You too can create your history here
                at The Manor.
              </p>
            </div>
          </div>
        </div>
        <div
          name="Rooms and Grounds text container"
          style={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            width: "66vw",
            height: "12vh",
            backgroundColor: "translucent",
            padding: "2rem", // Add padding to all sides
            boxSizing: "border-box", // Include padding in the total width and height
            color: "#48021e",
            fontSize: "1.5rem",
            textAlign: "center",
            fontFamily: "EB Garamond, sans-serif",
            fontWeight: "500",
            letterSpacing: "0.2rem",
          }}
        >
          <p>OUR ROOMS & GROUNDS</p>
        </div>
        <div
          name="Rooms & Grounds grid container"
          style={{
            display: "flex",
            flexWrap: "wrap",
            flexDirection: "row",
            justifyContent: "space-between",
            alignContent: "space-between",
            width: "66vw",
            height: "78vh",
            backgroundColor: "translucent",
            marginBottom: "12vh",
          }}
        >
          <div
            name="Shelly's-container"
            style={{
              display: "flex",
              flexDirection: "column",
              width: "21vw",
              height: "36vh",
              backgroundColor: "translucent",
            }}
          >
            <div
              name="Shelley's-image-container "
              style={{
                display: "flex",
                flexDirection: "column",
                width: "21vw",
                height: "28vh",
                backgroundColor: "translucent",
                cursor: "pointer",
              }}
            >
              <img
                src="images/plasshelleys.jpg"
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                }}
              ></img>
            </div>
            <div
              name="Shelley's-text-container"
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                width: "21vw",
                height: "8vh",
                backgroundColor: "translucent",
                borderBottom: "1px solid #EAEAEA",
                borderLeft: "1px solid #EAEAEA",
                borderRight: "1px solid #EAEAEA",
                boxSizing: "border-box", // Include padding in the total width and height
                fontFamily: "EB Garamond, sans-serif",
                letterSpacing: "0.05rem",
                fontSize: "1.1rem",
                fontWeight: "500",
                color: "#48021e",
              }}
            >
              <p>SHELLEYS' THEATRE</p>
            </div>
          </div>
          <div
            name="Maddocks-container"
            style={{
              display: "flex",
              flexDirection: "column",
              width: "21vw",
              height: "36vh",
              backgroundColor: "translucent",
            }}
          >
            <div
              name="Maddocks-image-container"
              style={{
                display: "flex",
                width: "21vw",
                height: "28vh",
                backgroundColor: "blue",
                cursor: "pointer",
              }}
            >
              <img
                src="images/plasmaddocks.jpg"
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                }}
              ></img>
            </div>
            <div
              name="Maddocks-text-container"
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                width: "21vw",
                height: "8vh",
                backgroundColor: "translucent",
                borderBottom: "1px solid #EAEAEA",
                borderLeft: "1px solid #EAEAEA",
                borderRight: "1px solid #EAEAEA",
                boxSizing: "border-box", // Include padding in the total width and height
                fontFamily: "EB Garamond, sans-serif",
                letterSpacing: "0.05rem",
                fontSize: "1.1rem",
                fontWeight: "500",
                color: "#48021e",
              }}
            >
              <p>THE WILLIAM MADOCKS ROOM</p>
            </div>
          </div>
          <div
            name="Hildas-container"
            style={{
              display: "flex",
              flexDirection: "column",
              width: "21vw",
              height: "36vh",
              backgroundColor: "translucent",
            }}
          >
            <div
              name="Hildas-image-container"
              style={{
                display: "flex",
                width: "21vw",
                height: "28vh",
                backgroundColor: "blue",
                cursor: "pointer",
              }}
            >
              <img
                src="images/plashildas.jpg"
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                }}
              ></img>
            </div>
            <div
              name="Hildas-text-container"
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                width: "21vw",
                height: "8vh",
                backgroundColor: "translucent",
                borderBottom: "1px solid #EAEAEA",
                borderLeft: "1px solid #EAEAEA",
                borderRight: "1px solid #EAEAEA",
                boxSizing: "border-box", // Include padding in the total width and height
                fontFamily: "EB Garamond, sans-serif",
                letterSpacing: "0.05rem",
                fontSize: "1.1rem",
                fontWeight: "500",
                color: "#48021e",
              }}
            >
              <p>MISS HILDA'S</p>
            </div>
          </div>
          <div
            name="Drawing-room-container"
            style={{
              display: "flex",
              flexDirection: "column",
              width: "21vw",
              height: "36vh",
              backgroundColor: "translucent",
            }}
          >
            <div
              name="Drawing-room-image-container"
              style={{
                display: "flex",
                width: "21vw",
                height: "28vh",
                backgroundColor: "blue",
                cursor: "pointer",
              }}
            >
              <img
                src="images/plasdrawingroom.jpg"
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                }}
              ></img>
            </div>
            <div
              name="Drawing-groom-text-container"
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                width: "21vw",
                height: "8vh",
                backgroundColor: "translucent",
                borderBottom: "1px solid #EAEAEA",
                borderLeft: "1px solid #EAEAEA",
                borderRight: "1px solid #EAEAEA",
                boxSizing: "border-box", // Include padding in the total width and height
                fontFamily: "EB Garamond, sans-serif",
                letterSpacing: "0.05rem",
                fontSize: "1.1rem",
                fontWeight: "500",
                color: "#48021e",
              }}
            >
              <p>DRAWING ROOM</p>
            </div>
          </div>
          <div
            name="Diner-container"
            style={{
              display: "flex",
              flexDirection: "column",
              width: "21vw",
              height: "36vh",
              backgroundColor: "translucent",
            }}
          >
            <div
              name="Diner-image-container"
              style={{
                display: "flex",
                width: "21vw",
                height: "28vh",
                backgroundColor: "blue",
                cursor: "pointer",
              }}
            >
              <img
                src="images/plasdining.jpg"
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                }}
              ></img>
            </div>
            <div
              name="Diner-text-container"
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                width: "21vw",
                height: "8vh",
                backgroundColor: "translucent",
                borderBottom: "1px solid #EAEAEA",
                borderLeft: "1px solid #EAEAEA",
                borderRight: "1px solid #EAEAEA",
                boxSizing: "border-box", // Include padding in the total width and height
                fontFamily: "EB Garamond, sans-serif",
                letterSpacing: "0.05rem",
                fontSize: "1.1rem",
                fontWeight: "500",
                color: "#48021e",
              }}
            >
              <p>BREAKFAST DINER</p>
            </div>
          </div>
          <div
            name="Grounds-container"
            style={{
              display: "flex",
              flexDirection: "column",
              width: "21vw",
              height: "36vh",
              backgroundColor: "translucent",
            }}
          >
            <div
              name="Grounds-image-container"
              style={{
                display: "flex",
                width: "21vw",
                height: "28vh",
                backgroundColor: "blue",
                cursor: "pointer",
              }}
            >
              <img
                src="images/plasgrounds.jpg"
                style={{
                  width: "100%",
                  height: "100%",
                  objectFit: "cover",
                }}
              ></img>
            </div>
            <div
              name="Grounds-text-container"
              style={{
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
                width: "21vw",
                height: "8vh",
                backgroundColor: "translucent",
                borderBottom: "1px solid #EAEAEA",
                borderLeft: "1px solid #EAEAEA",
                borderRight: "1px solid #EAEAEA",
                boxSizing: "border-box", // Include padding in the total width and height
                fontFamily: "EB Garamond, sans-serif",
                fontSize: "1.1rem",
                fontWeight: "500",
                letterSpacing: "0.05rem",
                color: "#48021e",
              }}
            >
              <p>GROUNDS</p>
            </div>
          </div>
        </div>
      </div>
      <div
        name="Footer-container"
        style={{
          width: "99.1vw",
          height: "20vh",
          backgroundColor: "#48021e",
          display: "flex",
          justifyContent: "center",
        }}
      >
        <div
          name="Footer-content-container"
          style={{
            width: "66vw",
            height: "100%",
            backgroundColor: "translucent",
            display: "flex",
            justifyContent: "flex-start",
          }}
        >
          <div
            name="Text-footer-div"
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              alignContent: "center",
              backgroundColor: "translucent",
              width: "32vw",
              height: "20vh",
              color: "white",
              fontFamily: "EB Garamond",
              fontSize: "0.75rem",
              fontStyle: "normal",
              fontWeight: "500",
            }}
          >
            <p>HILLTOP MANOR, TREMADOG, PORTHMADOG LL49 9RG</p>
            <p>TELEPHONE: +44 (0) 1766 514 682</p>
            <p>© 2023 HILLTOP MANOR | ALL RIGHTS RESERVED | COOKIE POLICY</p>
          </div>
          {/* <div
            name="travellers-choice-div"
            style={{
              display: "flex",
              flexDirection: "column",
              justifyContent: "center",
              backgroundColor: "translucent",
            }}
          >
            <img
              src="images/travellers-choice-21.png"
              style={{
                width: "auto",
                height: "60%",
              }}
            ></img>
          </div> */}
          <div
            name="socials-div"
            style={{
              display: "flex",
              flexDirection: "row",
              justifyContent: "flex-end",
              alignItems: "center",
              backgroundColor: "translucent",
              width: "100%",
              height: "100%",
              cursor: "pointer",
            }}
          >
            <img
              src="images/Socials.png"
              style={{
                width: "9vw",
                height: "3vh",
              }}
            ></img>
          </div>
        </div>
      </div>
    </>
  );
}
