import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import BookButton from "@/components/BookButton.jsx";
import AwardsButton from "@/components/AwardsButton.jsx";
import Columns from "@/components/Columns.jsx";
import Video from "@/components/Video.jsx";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Plas-Tan-Yr-Allt</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        name="main-container"
        style={{
          display: "flex",
          position: "relative",
          margin: "0 auto",
          justifyContent: "center",
          flex: 1,
          width: "66vw",
          height: "100vh",
          backgroundColor: "blue",
        }}
      >
        {/* <Columns /> */}
        <div
          name="header-container"
          style={{
            display: "flex",
            margin: "0 auto",
            flex: 1,
            alignItems: "center",
            width: "66vw",
            height: "13vh",
            backgroundColor: "translucent",
          }}
        >
          <div
            name="menu-div"
            style={{
              display: "flex",
              flex: "1",
              backgroundColor: "red",
              maxWidth: "30.4vw",
            }}
          >
            <img
              name="menu-image"
              src="/Frame 5.jpg"
              alt="A descriptive text about the image"
              width="30vw"
              height="50vh"
              style={{}}
            ></img>
          </div>
          {/* <img
            name="main-logo"
            src="/logo-1-red 1.jpg"
            alt="A descriptive text about the image"
            width="100vw"
            height="120vh"
            style={{
              position: "absolute",
              left: "50%",
              top: "6%",
              transform: "translate(-50%, -50%)",
            }}
          /> */}
          <div name="logo-div" style={{ display: "flex" }}>
            <img
              name="main-logo"
              src="/logo-1-red 1.jpg"
              alt="A descriptive text about the image"
              width="100vw"
              height="120vh"
              style={{}}
            />
          </div>
          <div
            name="header-buttons-container"
            style={{
              display: "flex",
              flex: "1",
              justifyContent: "flex-end",
              backgroundColor: "green",
              maxWidth: "30.4vw",
            }}
          >
            <BookButton />
            <AwardsButton />
          </div>
        </div>
        <Video />
        <div
          name="card-container"
          style={{
            display: "flex",
            position: "absolute",
            top: "50%",
            left: "50%",
            marginTop: "65vh",
            marginLeft: "-33vw",
            flex: 1,
            justifyContent: "center",
            width: "22vw",
            height: "60vh",
            backgroundColor: "blue",
          }}
        >
          <div name="card-container-left-text"></div>
        </div>
        <div
          name="card-container"
          style={{
            display: "flex",
            position: "absolute",
            top: "50%",
            right: "0%",
            marginTop: "65vh",
            marginLeft: "-33vw",
            flex: 1,
            justifyContent: "center",
            width: "44vw",
            height: "60vh",
            backgroundColor: "red",
          }}
        >
          <div name="card-container-left-text"></div>
        </div>
      </div>
    </>
  );
}
